[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read", path = "./broadcast" }]
remappings = [
  '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/',
]
[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/5VFdaww5aOIaM4i2D6FvqozH_vE13ecE"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/t6fzcdOOsB7zEPhV7CMRBlbtUEybtNLg"
anvil = "http://127.0.0.1:8545"
